# Generated by Django 3.2.1 on 2021-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_blogcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
