# Generated by Django 3.2.4 on 2021-06-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(),
        ),
    ]
